### ISSUE TITLE
SA2EventViewer/SAMDL: Continually advance or backtrack frame by frame by holding down Next/Previous Frame key.

### ISSUE THREAD

**Issue by Rarefoil** [X-Hax/sa_tools#177]
This is either somehow a bug with my system or something that wasn't implemented yet, but holding down the Next Frame key or the Previous Frame key does nothing, which are still their default assignments. This would be a nice way to slowly search through events and animations.

My SA Tools was last updated on June 19th, but I don't believe SA2EventViewer or SAMDL was updated after that.

**Comment by ItsEasyActually** [comment]
Almost certain the lack of this stems from the control overhaul that happened a good while back. Labeling it as both bug and enhancement since I'm unsure which this technically is.

**Comment by PiKeyAr** [comment]
From the description it sounds like the input system is actually working as intended. The "Next Frame" and "Previous Frame" actions are set up to trigger when a key is pressed, not held. That means the key has to be released before the action can happen. It would be easy to change the action type to make them trigger when a key is held down, but that will make it difficult to use when you just want to move one frame forward or back, because it will keep jumping as long as it receives keystrokes. There's no analog to "do it once, then make a brief pause and keep doing it" like with typing. I think the easiest way to resolve this would be to add a new pair of actions that trigger while the key is being held.

**Comment by Rarefoil** [comment]
> From the description it sounds like the input system is actually working as intended. The "Next Frame" and "Previous Frame" actions are set up to trigger when a key is pressed, not held. That means the key has to be released before the action can happen. It would be easy to change the action type to make them trigger when a key is held down, but that will make it difficult to use when you just want to move one frame forward or back, because it will keep jumping as long as it receives keystrokes. There's no analog to "do it once, then make a brief pause and keep doing it" like with typing. I think the easiest way to resolve this would be to add a new pair of actions that trigger while the key is being held.

I vote to use the less than/greater than keys for this. And since they're dedicated keys, you can choose between requiring constant input or as a toggle.

**Comment by PiKeyAr** [comment]
I added "hold to play" keys to SAMDL and SA2EventViewer. Default bindings are `.` to go forward and `,` to go backwards.
